# ==================================================
# 1D Input File from LMDZ
# ==================================================
# Path to the 1D LMDZ NetCDF file used as input.

LMDZ_output1D: '/home/grzegorc/AWACA/LMDZ/OUT_golden_case_v8/TEST-amip-ERA5-LAM.01_20250212_20250218_INS_histinsD17.nc'
#LMDZ_output1D: '/home/grzegorc/AWACA/LMDZ/OUT_golden_case_v5/TEST-amip-ERA5-LAM.01_20250212_20250218_INS_histinsDC.nc'
#LMDZ_output1D: '/home/grzegorc/NAWDIC/curtain_lmdz.nc'
blowing_snow: False

# ==================================================
# COSP Parameters
# ==================================================
# npoint  : total number of horizontal grid points
# nsubcol : number of subcolumns used by COSP
# nz      : number of vertical levels

nsubcol: 50
nz: 95

blowing_snow: False #TURN ON when using blowing snow of Vignon et al. (2026)
precip_adj: True #True #TURN ON for POPRECIP the new precip scheme of LMDZ: it  activate the precip adjustment of Hillman et al. (2018) based on the model precip fraction
convection: True #If you consider convective clouds of LMDZ

exp_rand: False  #TURN OFF for coherence with LMDZ: activate the max_random overlap from Raisanen et al. (2004) generator
sub_var: False  #TURN OFF for coherence with LMDZ: activate the subgrid variability across the subcolumns based on the Raisanen et al. (2004) generator
superposed_clouds: True


# Output NetCDF file produced by COSP
# (An additional COSP output file is generated internally and later read by PAMTRA.)
FOUTPUTcosp: '../data/my_outputs/Output_COSP.nc'

# ==================================================
# PAMTRA Parameters
# ==================================================

Where_is_radar: 'Ground' #Ground,Aicraft, Sat

# ##### For ground based radar 
Altitude_obs: 0.

# ##### For Sat 
Altitude_sat: 390000

# ##### for aircraft
Aircraft_alt_file: '/home/grzegorc/AWACA/LMDZ/OUT_golden_case_v8/Flight_altitude.nc'
Pointing: "up" #up,down,both

PamtraVerbose: 1 #Verbosity of PAMTRA
pp_deltaX: 4    #4 profiles in X per worker
pp_deltaY: 2    #2 profile in Y per worker

  
# isel and jsel define a subset of points to process.
# Allows you to run the simulator for a part of the dataset.
# This is especially useful when npoint is large: 

isel: 0 #1114 #288 starting index of the selection: should be smaller than jsel
jsel: 1 #134 #576 ending index of the selection: should be smaller than npoint 


### Radar configuration
Scattering: 'Ori2021_mix_column_dendrites' #Ice particle type for SSRGA: 
#Scattering: 'Ori2021_rimed_aggregate_dendrites' #Ice particle type for SSRGA: 
#Scattering names: Ori2021_mix_column_dendrites,Ori2021_rimed_aggregate_dendrites,Hogan2017_v1_aggregate_bullet_rosettes,Hogan2017_v2_aggregate_bullet_rosettes
Radar_type: 'BASTA' #MRR, STXPOL, BASTA (12.5m resolution), MIRA35C

custom_radar: False #if you want to define the radar characteristics by yourself

 ############### Custom radar (overrides instrument noise level defined in PAMTRA) ###############
# freq         : radar frequency (GHz)
# Beam_width   : beam width (°)
# Ze_noise_1km : noise level at 1 km (dBZ)
# dt           : time resolution (s)
# Vnyq         : Nyquist velocity (m s-1)
# nfft         : number of FFT points (bins in radar spectra)
freq:         95.0
Beam_width:   0.8
Ze_noise_1km: -200
dt:           9
Vnyq:         10
nfft:         512


### Pamtra running parameters
Run_pamtra: True      # If False, PAMTRA execution is skipped: useful for debugging
Run_parall: True     # Enable parallel processing (faster execution), necessary for doppler spectra
Run_spectra: False #True    # Compute Doppler spectra (increases a lot the computation time)
Write_output: True #True #True   # Write or not .nc output


  #FOUTPUTpamtra: "../Ouput_golden_case_D17_MIRAv6_ssrga_spectra_Ka.nc"
FOUTPUTpamtra: "../output/CONV.nc"

#FOUTPUTpamtra: "../NAWDIC.nc"
