# ==================================================
# 1D Input File from LMDZ
# ==================================================
# Path to the 1D LMDZ NetCDF file used as input.
# Commented alternatives:
#   /home/grzegorc/AWACA/LMDZ/OUT_golden_case_v9/TEST-amip-ERA5-LAM.01_20250212_20250218_INS_histinsD17.nc
#   /home/grzegorc/AWACA/EARTHCARE/LMDZ_traj1.nc
LMDZ_output1D: '/home/grzegorc/AWACA/EARTHCARE/LMDZ_traj2.nc'

 ###############  Point selection ###############
# isel and jsel define a subset of time points to process.
# Each time point corresponds to one atmospheric profile.
# Setting isel=0 and jsel='end' processes all profiles in the file.
# This is especially useful when the total number of profiles is large.
isel: 0
jsel: 'end'
step: 1

# ==================================================
# LMDZ Physics Options
# ==================================================
# blowing_snow : enable blowing snow scheme (Vignon et al. 2026)
# precip_adj   : enable precip adjustment: use it for POPRECIP (Hillman et al. 2018)
# convection   : include convective clouds of LMDZ
blowing_snow: False
precip_adj:   False
convection:   False

# ==================================================
# COSP Parameters
# ==================================================
# nsubcol   : number of subcolumns
# nz        : number of vertical levels (usually: 95)
# superposed_clouds  : can convective and large-scale clouds coexist ? Firts tests shows that it is better to consider their coexistance
# exp_rand  : max-random overlap generator (Raisanen et al. 2004) — keep it False for coherence with LMDZ (see cosp2_test.f90 to change the decorrelation length)
# sub_var   : subgrid variability across subcolumns (Raisanen et al. 2004) — keep it False for coherence with LMDZ (it is only used for ice and snow now, see cosp2_test.f90 to use it on for cloud and rain or to change the distribution function parameters)

nsubcol:  30
nz:       95
superposed_clouds: True 
exp_rand: False
sub_var:  False

# Output NetCDF file for COSP (no need to change it)
# (An additional internal COSP file is generated and later read by PAMTRA)
FOUTPUTcosp: '../data/my_outputs/Output_COSP.nc'


# ==================================================
# PAMTRA Parameters
# ==================================================

# Where_is_radar : Ground | Aircraft | Sat
# Pointing       : up | down | both
# Altitude_obs   : radar altitude for ground based-radar (m)
# Altitude_sat   : satellite altitude (m)
# Aircraft_alt_file : NetCDF file containing aircraft altitude
Where_is_radar:    'Ground'
Pointing:          'up'
Altitude_obs:      0.
Altitude_sat:      390000
Aircraft_alt_file: '/home/grzegorc/AWACA/LMDZ/OUT_golden_case_v8/Flight_altitude.nc'

# Scattering  : ice particle type for SSRGA
# Ori2021_mix_column_dendrites | Ori2021_rimed_aggregate_dendrites
# Hogan2017_v1_aggregate_bullet_rosettes | Hogan2017_v2_aggregate_bullet_rosettes
Scattering: 'Ori2021_mix_column_dendrites'

custom_radar: False #if you want to define the radar characteristics by yourself

 ############### Custom radar (overrides instrument noise level defined in PAMTRA) ###############
# freq         : radar frequency (GHz)
# Beam_width   : beam width (°)
# Ze_noise_1km : noise level at 1 km (dBZ)
# dt           : time resolution (s)
# Vnyq         : Nyquist velocity (m s-1)
# nfft         : number of FFT points (bins in radar spectra)
freq:         95.0
Beam_width:   0.8
Ze_noise_1km: -200
dt:           9
Vnyq:         10
nfft:         512

 ############### Predefined radar characteristics (used if custom_radar: False) ###############
# Radar_type  : MRR | STXPOL | BASTA (dz = 12.5) | MIRA35C | EarthCARE_cpr
Radar_type: 'BASTA'

 ############### Execution options ###############
# Run_pamtra  : if False, PAMTRA execution is skipped (useful for debugging)
# Run_parall  : enable parallel processing (better for Doppler spectra)
# Run_spectra : compute Doppler spectra (significantly increases computation time)
# Write_output: write NetCDF output file
Run_pamtra:   True
Run_parall:   True
Run_spectra:  False
Write_output: True

# PamtraVerbose: verbosity level of PAMTRA
# pp_deltaX    : Parallel run: number of profiles in X per core
# pp_deltaY    : Parallel run: number of profiles in Y per core
PamtraVerbose: 1
pp_deltaX:     4
pp_deltaY:     2

# Output NetCDF file for PAMTRA
FOUTPUTpamtra: '../output/Earthcare_traj2.nc'
